In [4]:
# NumPy 
import numpy as np

In [44]:
# Create a numpy array from a list
arr = np.array([1, 2, 3, 4, 5, 6])

In [45]:
# Views the array
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
# Type of array
# It is not a list
# It is a NumPy array (numpy.ndarray)
type(arr)

numpy.ndarray

In [10]:
# Make an array which
# Starts at 1
# Ends at 100 (not included)
# Interval 3
np.arange(1,100,3)
# This same concept can be used to make similar arrays

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [46]:
np.arange(7, 7000, 153)

array([   7,  160,  313,  466,  619,  772,  925, 1078, 1231, 1384, 1537,
       1690, 1843, 1996, 2149, 2302, 2455, 2608, 2761, 2914, 3067, 3220,
       3373, 3526, 3679, 3832, 3985, 4138, 4291, 4444, 4597, 4750, 4903,
       5056, 5209, 5362, 5515, 5668, 5821, 5974, 6127, 6280, 6433, 6586,
       6739, 6892])

In [11]:
# Make an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# Make an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# To make an array of another number (e.g. 5, use this way)
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
# You can have other operations too (-, *, /)
np.ones(10) - 0.12756947

array([0.87243053, 0.87243053, 0.87243053, 0.87243053, 0.87243053,
       0.87243053, 0.87243053, 0.87243053, 0.87243053, 0.87243053])

In [19]:
np.ones(10) * 3.14

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [20]:
np.ones(10) / 89

array([0.01123596, 0.01123596, 0.01123596, 0.01123596, 0.01123596,
       0.01123596, 0.01123596, 0.01123596, 0.01123596, 0.01123596])

In [38]:
np.ones(10) ** 4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
# Make 2 dimensional arrays 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# np.eye makes an array with ones in a diagonal, zeros to fill the rest
# Parameter taken is the number of rows 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# np.linspace returns an array with numbers equally spaced in the range (range is first to params)
# third parameter is the number of numbers
np.linspace(1,1000,50)

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [27]:
# np.random.rand returns an array of random numbers between 0 and 1
# To get the values more than 1, use the operations
x = np.random.rand(5,5)

In [28]:
x

array([[0.29125736, 0.87993067, 0.56833511, 0.65240624, 0.76001694],
       [0.54839673, 0.53130171, 0.70397048, 0.30218863, 0.71547983],
       [0.22396805, 0.25269308, 0.99918745, 0.19094623, 0.7783792 ],
       [0.63181324, 0.28392742, 0.47461309, 0.83766815, 0.18199962],
       [0.22700017, 0.07316009, 0.90760854, 0.02707398, 0.08330402]])

In [47]:
np.random.rand(5, 5) + 7

array([[7.90480963, 7.39158845, 7.26649666, 7.35414604, 7.08461454],
       [7.46009171, 7.50809996, 7.5968866 , 7.68838906, 7.27575007],
       [7.20535122, 7.93778508, 7.00533763, 7.0875753 , 7.52656844],
       [7.20938252, 7.84022376, 7.9138607 , 7.40172544, 7.53024734],
       [7.62935981, 7.44232882, 7.82705816, 7.86837726, 7.04966686]])

In [29]:
# Get minimum
x.min()

0.02707397958909985

In [30]:
# Get max
x.max()

0.9991874540199893

In [31]:
# Indexing
x[0, 3]

0.6524062366581922

In [32]:
# Slicing
x[1:4,2:4]

array([[0.70397048, 0.30218863],
       [0.99918745, 0.19094623],
       [0.47461309, 0.83766815]])

In [34]:
# Will change those 6 values above to 0.14159
x[1:4,2:4]= 0.14159  # Broadcasting

In [35]:
x

array([[0.29125736, 0.87993067, 0.56833511, 0.65240624, 0.76001694],
       [0.54839673, 0.53130171, 0.14159   , 0.14159   , 0.71547983],
       [0.22396805, 0.25269308, 0.14159   , 0.14159   , 0.7783792 ],
       [0.63181324, 0.28392742, 0.14159   , 0.14159   , 0.18199962],
       [0.22700017, 0.07316009, 0.90760854, 0.02707398, 0.08330402]])

In [37]:
x[x>0.5] # Conditional Indexing 
# Getting all numbers in the array which are above 0.5
# All Python COndional Rules apply in the example above
# 'and', 'or', 'not', ==, >=, <=, <, >

array([0.87993067, 0.56833511, 0.65240624, 0.76001694, 0.54839673,
       0.53130171, 0.71547983, 0.7783792 , 0.63181324, 0.90760854])

In [39]:
# Saving array to file
randarr = np.random.rand(5, 5)

In [40]:
randarr

array([[0.00157986, 0.30846544, 0.98265559, 0.83657744, 0.72629394],
       [0.6177294 , 0.31032857, 0.59323062, 0.56535117, 0.34762965],
       [0.19805139, 0.77377417, 0.34767532, 0.18059949, 0.38040255],
       [0.88014311, 0.12455844, 0.27447363, 0.70557018, 0.84161729],
       [0.1948903 , 0.21346648, 0.30794589, 0.24937718, 0.36077335]])

In [41]:
# Save 
np.save("myseries.npy",randarr)

In [42]:
# Load array
myarr=np.load("myseries.npy")

In [43]:
myarr

array([[0.00157986, 0.30846544, 0.98265559, 0.83657744, 0.72629394],
       [0.6177294 , 0.31032857, 0.59323062, 0.56535117, 0.34762965],
       [0.19805139, 0.77377417, 0.34767532, 0.18059949, 0.38040255],
       [0.88014311, 0.12455844, 0.27447363, 0.70557018, 0.84161729],
       [0.1948903 , 0.21346648, 0.30794589, 0.24937718, 0.36077335]])